modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
description = '''${mod_description}'''

[[dependencies.cobble_contests]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobble_contests]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobble_contests]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6,)"
ordering = "NONE"
side = "BOTH"
